inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-minitest

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Minitest/AssertInDelta:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
